In [1]:
namelist='ramya','bhattu'
namelist

('ramya', 'bhattu')

In [2]:
name list='ramya','bhattu'
name list


SyntaxError: invalid syntax (25212798.py, line 1)

### space is not allowed

## List

In [3]:
sample_list=[1,2,3,4,-1,'hi',5.7,1,1,-1]
sample_list

[1, 2, 3, 4, -1, 'hi', 5.7, 1, 1, -1]

In [4]:
type(sample_list)

list

In [6]:
sample_list[5]

'hi'

In [7]:
sample_list[10]

IndexError: list index out of range

In [8]:
sample_list[-5]

'hi'

In [10]:
sample_list[0]=100
sample_list

[100, 2, 3, 4, -1, 'hi', 5.7, 1, 1, -1]

### elements in a list are seperated by comma and enclosed in square brackets

##### list is heterogeneous-> Multiple data types

##### list can have duplicates

##### list is mutable -> make changes

In [11]:
book_list=['python','R','DS']
print(book_list)
type(book_list)

['python', 'R', 'DS']


list

## Tuple

##### 1) Container Object

##### 2) Heterogeneous-> allows multiple data types

##### 3) can have duplicates

##### 4) immutable-> cannot make changes

##### 5) Elements are seperated by comma,enclosed in paranthesis or without any brackets

In [14]:
sample_tuple=(1,6,2.3,8.3,'hi')
sample_tuple

(1, 6, 2.3, 8.3, 'hi')

In [15]:
type(sample_tuple)

tuple

In [16]:
sample_tuple2=1,6,2.3,8.3,'hi'
sample_tuple2

(1, 6, 2.3, 8.3, 'hi')

In [17]:
type(sample_tuple2)


tuple

In [18]:
print(sample_tuple)
print(sample_tuple2)


(1, 6, 2.3, 8.3, 'hi')
(1, 6, 2.3, 8.3, 'hi')


In [19]:
sample_tuple[1]

6

In [20]:
sample_tuple[10]

IndexError: tuple index out of range

In [21]:
sample_tuple[0]=100

TypeError: 'tuple' object does not support item assignment

 ##    Dictionary
    
##### 1) Key-value pair
    
##### 2) {} -> curly brackets
    
##### 3) Indexing-square bracket
    
##### 4) Mutable

In [22]:
dict_1={'name': 'ramya','hobbies':['painting','singing','cooking'],1:23}
type(dict_1)
dict_1

{'name': 'ramya', 'hobbies': ['painting', 'singing', 'cooking'], 1: 23}

In [23]:
dict_1[keys]

NameError: name 'keys' is not defined

In [24]:
dict_1.keys()

dict_keys(['name', 'hobbies', 1])

In [25]:
dict_1.values()


dict_values(['ramya', ['painting', 'singing', 'cooking'], 23])

In [28]:
dict_1['name']='srilatha'

In [29]:
dict_1.keys()

dict_keys(['name', 'hobbies', 1])

In [30]:
dict_1.values()

dict_values(['srilatha', ['painting', 'singing', 'cooking'], 23])

## SET
##### 1) Set doesn't allow duplicates
##### 2) It will get sorted according to the alphabetical order


In [32]:
sample_set={1,2,3,4,5,1,13.4,9.6,'hi','hello','ds',-1,11.4,21.5}
sample_set

{-1, 1, 11.4, 13.4, 2, 21.5, 3, 4, 5, 9.6, 'ds', 'hello', 'hi'}

In [33]:
sample_set[0]

TypeError: 'set' object is not subscriptable

##### 3)indexing will not work

In [34]:
sample_set[0]=1

TypeError: 'set' object does not support item assignment

##### for indexing slicing or list only we will use square bracket

## Numpy: Package for multidimensional array

### Numpy-> Play with arrays or numbers
### Pandas-> Dataset
### Matplotlib-> Data visualisation
### Seaborn-> Data visualisation
### Scipy-> Statistical
### Sklearn-> Algorithm

In [35]:
import numpy as np


In [36]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [37]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [38]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [41]:
np.arange(1,35,4) #shift+tab-> help box

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33])

In [42]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [46]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [48]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [50]:
np.zeros(100,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [53]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [54]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [55]:
np.linspace(10,50,5)

array([10., 20., 30., 40., 50.])

In [56]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [57]:
np.random.rand(3,5)

array([[0.64319729, 0.9428936 , 0.96484489, 0.37126714, 0.23876955],
       [0.5777494 , 0.3673963 , 0.2173896 , 0.29981928, 0.01575296],
       [0.40279049, 0.40347337, 0.66773288, 0.7141075 , 0.86884496]])

In [58]:
np.random.rand(3,5)

array([[0.18063884, 0.57076606, 0.3290854 , 0.12287146, 0.56103794],
       [0.87397218, 0.69137615, 0.7953771 , 0.1893951 , 0.94210561],
       [0.33619224, 0.4225521 , 0.12321239, 0.36365109, 0.20954251]])

In [59]:
arr=np.random.rand(5,6)
arr

array([[0.04380272, 0.37327482, 0.60001374, 0.63970784, 0.24452919,
        0.23380867],
       [0.2249252 , 0.87240095, 0.21993794, 0.11118334, 0.7791516 ,
        0.73230776],
       [0.66638957, 0.36996948, 0.88535605, 0.95744485, 0.60563635,
        0.37008446],
       [0.01491807, 0.05331643, 0.48787981, 0.7376661 , 0.2667769 ,
        0.03341965],
       [0.45065913, 0.64613616, 0.29280336, 0.30919005, 0.58543004,
        0.67415588]])

In [60]:
np.random.randn(2,4)


array([[ 0.68920652,  0.79631927,  2.3888322 ,  1.20062611],
       [ 1.40932664,  0.95003909, -0.53331202,  0.11192363]])

In [61]:
np.random.randint(2,4)

3

In [62]:
np.random.randint(2,100)

35

In [63]:
np.random.randint(20,56,100)

array([21, 38, 47, 34, 36, 51, 35, 36, 25, 52, 51, 34, 55, 38, 29, 44, 38,
       51, 41, 23, 51, 22, 31, 42, 33, 43, 33, 31, 32, 43, 28, 48, 50, 45,
       46, 39, 48, 47, 36, 40, 49, 45, 25, 51, 48, 49, 51, 50, 49, 23, 28,
       37, 26, 25, 35, 31, 34, 55, 29, 31, 39, 52, 29, 42, 52, 22, 37, 25,
       48, 33, 20, 55, 49, 50, 36, 31, 53, 38, 35, 45, 37, 20, 42, 48, 27,
       42, 43, 44, 36, 22, 33, 52, 55, 52, 50, 53, 51, 43, 29, 22])

In [65]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [66]:
rand_array=np.random.randint(0,20,50)
rand_array

array([12, 16,  1,  3, 12,  2,  3, 12, 15, 16,  3, 17, 10,  2, 16,  1,  5,
        3, 10, 15,  4, 17,  3,  3, 17, 14, 14, 18, 17, 12, 14,  2, 12,  5,
        3, 15,  3,  9,  2, 19,  8,  0,  7, 13,  4, 13,  4, 15,  2, 12])

In [71]:
sample_array.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [72]:
sample_array.reshape(4,5)

ValueError: cannot reshape array of size 30 into shape (4,5)